volumes:
    mysqldata:
        driver: local

services:

    mysql:
        image: 'mysql:8.0'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 1q2w3e4r
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wp
            MYSQL_PASSWORD: 1q2w3e4r
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    www:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./app:/var/www/html
            - ./var/debug.log:/var/www/log/debug.log
        ports:
            - '80:80'
        environment:
            # HTTP_HOST: http://localhost:80
            # WORDPRESS_DB_HOST: mysql:3306      # default
            # WORDPRESS_DB_NAME: wordpress  # default
            WORDPRESS_TABLE_PREFIX: wpb_
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: 1q2w3e4r
        depends_on:
            mysql:
                condition: service_healthy

    pma:
        image: 'phpmyadmin/phpmyadmin'
        ports:
            - '9020:80'
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: 1q2w3e4r
